version: '3.3'
services:
  level3:
    build:
      context: ./
    image: pctf21_bluewhale_lvl3:latest
    container_name: bluewhale_lvl3
    volumes:
      - ./app:/root/app
      - ./algorithm.py:/root/app/modules/algorithm.py
      - ./keys:/root/keys
      - ./keys/config.json:/home/cobb/keys_config.json
      - ./algorithm.py:/home/cobb/jail/algorithm.py
      - ./security/jail.bashrc:/home/cobb/.bashrc
      - ./security/jail.profile:/home/cobb/.profile
      - ./security/limits.conf:/etc/security/limits.conf
      - ./startup.sh:/root/startup.sh
    restart: always
    tty: true
    hostname: bluewhale-3
    privileged: true
    command: /root/startup.sh
    ports:
      - "4000:3000"
