version: '3.3'
services:
  lovemeornot:
    build:
      context: ./Docker
    image: pctf21_lovemeornot:latest
    restart: always
    privileged: true
    entrypoint: /bin/bash
    command: /home/ctf/startup.sh
    ports:
      - "3002:3000"

networks:
  default:
    name: pctf21_lovemeornot
    driver: bridge
