version: '3.3'
services:
  spectral:
    build:
      context: ./Docker
    image: pctf21_spectral:latest
    restart: always
    privileged: true
    entrypoint: /bin/bash
    command: /home/ctf/startup.sh
    ports:
      - "3001:3000"

networks:
  default:
    name: pctf21_spectral
    driver: bridge
