version: "3"
services:
    notrockyouserver:
        container_name: notrockyouserver
        build: ./server
        restart: always
        ports:
            - "8000:8000"
        depends_on:
            - notrockyoudb

    notrockyoudb:
        container_name: notrockyoudb
        image: mongo:latest
        restart: always
        ports:
            - "27019:27017"
        volumes:
            - ./db/data:/data/db
        env_file:
            - .env
