version: "3"

services:
    santanode:
        container_name: santanode
        build: ./nodeapp
        restart: always
        ports:
            - "8000:8000"
        depends_on:
            - santamongo

    santamongo:
        container_name: santamongo
        image: mongo:latest
        restart: always
        env_file:
            - .env
        ports:
            - "27018:27017"
        volumes:
            - ./mongocontainer/mongodata:/data/db
    santabot:
        container_name: santabot
        build: ./xssbot
        restart: always
        depends_on:
            - santamongo
