version: "3"

services:
    nodeapp:
        container_name: nodeapp
        build: ./nodeapp
        restart: always
        ports:
            - "8000:8000"
        depends_on:
            - mongocontainer

    mongocontainer:
        container_name: mongocontainer
        build: ./mongocontainer
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - "27018:27017"
        volumes:
            - ./mongocontainer/mongodata:/data/db
