version: '3.3'
services:
  level2:
    build:
      context: ./
    image: pctf21_bluewhale_lvl2:latest
    container_name: bluewhale_lvl2
    volumes:
      - ./app:/root/app
      - ./algorithm.py:/root/app/modules/algorithm.py
      - ./shell:/home/cobb/shell
      - ./bashrc/shell.bashrc:/home/cobb/.bashrc
      - ./bashrc/jail.bashrc:/home/prisoner/.bashrc
      - ./startup.sh:/root/startup.sh
      - ./level_3:/root/level_3
      - ./algorithm.py:/root/level_3/algorithm.py
    restart: always
    tty: true
    hostname: bluewhale-2
    privileged: true
    command: /root/startup.sh
    ports:
      - "3000:3000"
