version: '3.3'
services:
#  db:
#    build:
#      context: ./db
#      args:
#        - DB_NAME
#        - DB_ROOT_PASSWORD
#    image: pctf21_schrodinger_db:latest
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
#      MYSQL_DATABASE: "${DB_NAME}"

  app:
    build:
      context: ./app
      args:
        - FLAG
        - IMAGE_URL
        - SSH_USER_PASSWORD
        - SSH_PORT
        - DB_HOST
        - DB_PORT
        - DB_NAME
        - DB_ROOT_PASSWORD
        - DB_ICECREAM_TABLE
    image: pctf21_schrodinger_app:latest
#    depends_on:
#      - db
    restart: always
    environment:
      DEBIAN_FRONTEND: noninteractive
    ports:
      - "${APP_PORT}:80"
  
  ssh:
    build:
      context: ./ssh
      args:
        - SSH_TIMEZONE
        - SSH_USERNAME
        - SSH_ROOT_PASSWORD
        - SSH_USER_PASSWORD
        - DB_HOST
        - DB_PORT
        - DB_NAME
        - DB_ROOT_PASSWORD
        - DB_ID_TABLE
        - DB_ICECREAM_TABLE
        - ADMIN_USERNAME
        - ADMIN_EMAIL
        - ADMIN_PASSWORD
    image: pctf21_schrodinger_ssh:latest
    depends_on:
#      - db
      - app
    restart: always
    tty: true
    privileged: true
    environment:
      DEBIAN_FRONTEND: noninteractive
    cap_add:
      - NET_ADMIN
    ports:
      - "${SSH_PORT}:22"

networks:
  default:
    name: pctf21_schrodinger
    driver: bridge
