#build time: 16min
version: '3.3'
services:
  level1:
    build:
      context: ./
      args:
        - PROC_LIMIT=1000
    image: pctf21_bluewhale_lvl1:latest
    container_name: bluewhale
    volumes:
      - ./shell:/home/cobb/shell
      - ./config/sshd_config:/etc/ssh/sshd_config
      - ./config/jail.local:/etc/fail2ban/jail.local
      - ./jail.bashrc:/home/prisoner/.bashrc
      - ./startup.sh:/root/startup.sh
      - ./level_2:/root/level_2
      - ./jail.bashrc:/root/level_2/bashrc/jail.bashrc
    restart: always
    tty: true
    hostname: bluewhale
    cap_add:
      - NET_ADMIN
    privileged: true
    command: /root/startup.sh
    ports:
      - "4002:22"

networks:
  default:
    name: pctf21_bluewhale
    driver: bridge
